// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerTournamentDirector.Data;

#nullable disable

namespace PokerTournamentDirector.Migrations
{
    [DbContext(typeof(PokerDbContext))]
    [Migration("20260121100809_InitialCreateWithPokerTables")]
    partial class InitialCreateWithPokerTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PokerTournamentDirector.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DangerColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultBreakDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultLevelDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSounds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoundOn10Seconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOn60Seconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnCountdown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnLevelChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnPauseResume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarningColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BigBlind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlindStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreakName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmallBlind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId", "LevelNumber");

                    b.ToTable("BlindLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ante = 0,
                            BigBlind = 50,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 1,
                            SmallBlind = 25
                        },
                        new
                        {
                            Id = 2,
                            Ante = 0,
                            BigBlind = 100,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 2,
                            SmallBlind = 50
                        },
                        new
                        {
                            Id = 3,
                            Ante = 0,
                            BigBlind = 150,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 3,
                            SmallBlind = 75
                        },
                        new
                        {
                            Id = 4,
                            Ante = 25,
                            BigBlind = 200,
                            BlindStructureId = 1,
                            BreakName = "Pause 15 min",
                            DurationMinutes = 15,
                            IsBreak = true,
                            LevelNumber = 4,
                            SmallBlind = 100
                        },
                        new
                        {
                            Id = 5,
                            Ante = 25,
                            BigBlind = 300,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 5,
                            SmallBlind = 150
                        },
                        new
                        {
                            Id = 6,
                            Ante = 50,
                            BigBlind = 400,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 6,
                            SmallBlind = 200
                        },
                        new
                        {
                            Id = 7,
                            Ante = 75,
                            BigBlind = 600,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 7,
                            SmallBlind = 300
                        },
                        new
                        {
                            Id = 8,
                            Ante = 100,
                            BigBlind = 800,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 8,
                            SmallBlind = 400
                        },
                        new
                        {
                            Id = 9,
                            Ante = 100,
                            BigBlind = 1000,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 9,
                            SmallBlind = 500
                        },
                        new
                        {
                            Id = 10,
                            Ante = 200,
                            BigBlind = 1200,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 10,
                            SmallBlind = 600
                        },
                        new
                        {
                            Id = 11,
                            Ante = 0,
                            BigBlind = 50,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 1,
                            SmallBlind = 25
                        },
                        new
                        {
                            Id = 12,
                            Ante = 0,
                            BigBlind = 100,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 2,
                            SmallBlind = 50
                        },
                        new
                        {
                            Id = 13,
                            Ante = 25,
                            BigBlind = 200,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 3,
                            SmallBlind = 100
                        },
                        new
                        {
                            Id = 14,
                            Ante = 25,
                            BigBlind = 300,
                            BlindStructureId = 2,
                            BreakName = "Pause 10 min",
                            DurationMinutes = 10,
                            IsBreak = true,
                            LevelNumber = 4,
                            SmallBlind = 150
                        },
                        new
                        {
                            Id = 15,
                            Ante = 50,
                            BigBlind = 400,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 5,
                            SmallBlind = 200
                        },
                        new
                        {
                            Id = 16,
                            Ante = 75,
                            BigBlind = 600,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 6,
                            SmallBlind = 300
                        },
                        new
                        {
                            Id = 17,
                            Ante = 100,
                            BigBlind = 1000,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 7,
                            SmallBlind = 500
                        },
                        new
                        {
                            Id = 18,
                            Ante = 200,
                            BigBlind = 1600,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 8,
                            SmallBlind = 800
                        });
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlindStructures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 21, 11, 8, 9, 406, DateTimeKind.Local).AddTicks(2748),
                            Description = "Structure classique pour home games",
                            Name = "Standard (2h)"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 21, 11, 8, 9, 406, DateTimeKind.Local).AddTicks(2896),
                            Description = "Structure rapide, niveaux de 12 minutes",
                            Name = "Turbo (1h30)"
                        });
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalITM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTournamentsPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalWinnings")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PlayerRebuy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RebuyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RebuyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("PlayerRebuys");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PokerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("PokerTable");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AddOnAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddOnAtLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddOnStack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAddOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowBounty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRebuys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlindStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BountyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BountyType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuyIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CurrentLevelStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LateRegistrationLevels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRebuysPerPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutStructureJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rake")
                        .HasColumnType("TEXT");

                    b.Property<int>("RakeType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RebuyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RebuyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyLimitType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyMaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyPeriodMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyStack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyUntilPlayersLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatsPerTable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingStack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAddOns")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrizePool")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRebuys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId");

                    b.HasIndex("Date");

                    b.HasIndex("TemplateId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BountyKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionshipPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EliminatedByPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EliminationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAddOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Winnings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TableId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPlayers");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AddOnAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddOnAtLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddOnStack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAddOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowBounty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRebuys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlindStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BountyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BountyType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuyIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("LateRegLevels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRebuysPerPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutStructureJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rake")
                        .HasColumnType("TEXT");

                    b.Property<int>("RakeType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RebuyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RebuyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyLimitType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyMaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyPeriodMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyStack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyUntilPlayersLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatsPerTable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingStack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId");

                    b.ToTable("TournamentTemplates");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindLevel", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.BlindStructure", "BlindStructure")
                        .WithMany("Levels")
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlindStructure");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PlayerRebuy", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Player", "Player")
                        .WithMany("Rebuys")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany("Rebuys")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PokerTable", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany("Tables")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Tournament", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.BlindStructure", "BlindStructure")
                        .WithMany()
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.TournamentTemplate", "Template")
                        .WithMany("TournamentsCreated")
                        .HasForeignKey("TemplateId");

                    b.Navigation("BlindStructure");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentPlayer", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Player", "Player")
                        .WithMany("TournamentParticipations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.PokerTable", "Table")
                        .WithMany("Players")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Table");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentTemplate", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.BlindStructure", "BlindStructure")
                        .WithMany()
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlindStructure");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindStructure", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Player", b =>
                {
                    b.Navigation("Rebuys");

                    b.Navigation("TournamentParticipations");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PokerTable", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Tournament", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Rebuys");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentTemplate", b =>
                {
                    b.Navigation("TournamentsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
