// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerTournamentDirector.Data;

#nullable disable

namespace PokerTournamentDirector.Migrations
{
    [DbContext(typeof(PokerDbContext))]
    [Migration("20260201012338_AddBirthDateToPlayer")]
    partial class AddBirthDateToPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PokerTournamentDirector.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdministrativeDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnualFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DangerColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultBreakDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultLevelDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableProrata")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearEndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearEndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallmentOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProrataMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoundOn10Seconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOn60Seconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnBreak")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnCountdown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnKill")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnLevelChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnPauseResume")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnRebuy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnUndoKill")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundOnWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrialPeriodWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarningColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BigBlind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlindStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreakName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmallBlind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId", "LevelNumber");

                    b.ToTable("BlindLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ante = 0,
                            BigBlind = 50,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 1,
                            SmallBlind = 25
                        },
                        new
                        {
                            Id = 2,
                            Ante = 0,
                            BigBlind = 100,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 2,
                            SmallBlind = 50
                        },
                        new
                        {
                            Id = 3,
                            Ante = 0,
                            BigBlind = 150,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 3,
                            SmallBlind = 75
                        },
                        new
                        {
                            Id = 4,
                            Ante = 25,
                            BigBlind = 200,
                            BlindStructureId = 1,
                            BreakName = "Pause 15 min",
                            DurationMinutes = 15,
                            IsBreak = true,
                            LevelNumber = 4,
                            SmallBlind = 100
                        },
                        new
                        {
                            Id = 5,
                            Ante = 25,
                            BigBlind = 300,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 5,
                            SmallBlind = 150
                        },
                        new
                        {
                            Id = 6,
                            Ante = 50,
                            BigBlind = 400,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 6,
                            SmallBlind = 200
                        },
                        new
                        {
                            Id = 7,
                            Ante = 75,
                            BigBlind = 600,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 7,
                            SmallBlind = 300
                        },
                        new
                        {
                            Id = 8,
                            Ante = 100,
                            BigBlind = 800,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 8,
                            SmallBlind = 400
                        },
                        new
                        {
                            Id = 9,
                            Ante = 100,
                            BigBlind = 1000,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 9,
                            SmallBlind = 500
                        },
                        new
                        {
                            Id = 10,
                            Ante = 200,
                            BigBlind = 1200,
                            BlindStructureId = 1,
                            DurationMinutes = 20,
                            IsBreak = false,
                            LevelNumber = 10,
                            SmallBlind = 600
                        },
                        new
                        {
                            Id = 11,
                            Ante = 0,
                            BigBlind = 50,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 1,
                            SmallBlind = 25
                        },
                        new
                        {
                            Id = 12,
                            Ante = 0,
                            BigBlind = 100,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 2,
                            SmallBlind = 50
                        },
                        new
                        {
                            Id = 13,
                            Ante = 25,
                            BigBlind = 200,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 3,
                            SmallBlind = 100
                        },
                        new
                        {
                            Id = 14,
                            Ante = 25,
                            BigBlind = 300,
                            BlindStructureId = 2,
                            BreakName = "Pause 10 min",
                            DurationMinutes = 10,
                            IsBreak = true,
                            LevelNumber = 4,
                            SmallBlind = 150
                        },
                        new
                        {
                            Id = 15,
                            Ante = 50,
                            BigBlind = 400,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 5,
                            SmallBlind = 200
                        },
                        new
                        {
                            Id = 16,
                            Ante = 75,
                            BigBlind = 600,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 6,
                            SmallBlind = 300
                        },
                        new
                        {
                            Id = 17,
                            Ante = 100,
                            BigBlind = 1000,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 7,
                            SmallBlind = 500
                        },
                        new
                        {
                            Id = 18,
                            Ante = 200,
                            BigBlind = 1600,
                            BlindStructureId = 2,
                            DurationMinutes = 12,
                            IsBreak = false,
                            LevelNumber = 8,
                            SmallBlind = 800
                        });
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlindStructures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 1, 2, 23, 38, 641, DateTimeKind.Local).AddTicks(2145),
                            Description = "Structure classique pour home games",
                            IsFavorite = false,
                            Name = "Standard (2h)"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 1, 2, 23, 38, 641, DateTimeKind.Local).AddTicks(2301),
                            Description = "Structure rapide, niveaux de 12 minutes",
                            IsFavorite = false,
                            Name = "Turbo (1h30)"
                        });
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Championship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowLateRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRetroactivePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestXOfSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestXPerMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestXPerQuarter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CountBounties")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountingMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultMatchCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableMonthlyStandings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableParticipationPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableQuarterlyStandings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSeasonPrizes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExcludeWorstX")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FinalMatchCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstEliminatedConsolation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixedPointsTable")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GenerateProvisionalAfterEachMatch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpenChampionship")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LateRegistrationUntilMatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinearFirstPlacePoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MainEventCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipationPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsPerBounty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrizeDistribution")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProportionalTotalPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualificationMinMatches")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualificationMinPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualificationTopX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyMode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RebuyPointsMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<int>("RebuyPointsPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SeasonPrizePool")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeColor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiebreaker1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Tiebreaker2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Tiebreaker3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Top3Bonus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VictoryBonus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Championships");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.ChampionshipLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterData")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeData")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.ToTable("ChampionshipLogs");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.ChampionshipMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMainEvent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("TournamentId");

                    b.ToTable("ChampionshipMatches");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.ChampionshipStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageMinutesPerMatch")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePosition")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BestPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EliminatedMostByPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EliminatedMostPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQualified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonthlyPoints")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PositionStdDev")
                        .HasColumnType("REAL");

                    b.Property<int?>("PreviousPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuarterlyPoints")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROI")
                        .HasColumnType("TEXT");

                    b.Property<int>("RebuysUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Top3Finishes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBounties")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMinutesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalWinnings")
                        .HasColumnType("TEXT");

                    b.Property<int>("Victories")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorstPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ChampionshipStandings");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PaymentSchedules");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstallmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTournamentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Paid")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalDue")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalITM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTournamentsPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalWinnings")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TrialEnd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PlayerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerLogs");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PlayerRebuy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RebuyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RebuyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("PlayerRebuys");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PokerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("PokerTable");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AddOnAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddOnAtLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddOnStack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAddOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowBounty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRebuys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlindStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BountyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BountyType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuyIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CurrentLevelStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LateRegistrationLevels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRebuysPerPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutStructureJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rake")
                        .HasColumnType("TEXT");

                    b.Property<int>("RakeType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RebuyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RebuyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyLimitType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyMaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyPeriodMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyStack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyUntilPlayersLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatsPerTable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingStack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAddOns")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrizePool")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRebuys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId");

                    b.HasIndex("Date");

                    b.HasIndex("TemplateId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayersRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentLogs");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BountyKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionshipPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EliminatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EliminatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EliminatedByPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EliminationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAddOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Winnings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TableId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPlayers");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AddOnAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AddOnAtLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddOnStack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAddOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowBounty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRebuys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlindStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BountyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BountyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("LateRegLevels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRebuysPerPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutStructureJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rake")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RakeType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RebuyAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RebuyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyLimitType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyMaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RebuyPeriodMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyStack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RebuyUntilPlayersLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatsPerTable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingStack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlindStructureId");

                    b.ToTable("TournamentTemplates");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindLevel", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.BlindStructure", "BlindStructure")
                        .WithMany("Levels")
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlindStructure");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.ChampionshipLog", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Championship", "Championship")
                        .WithMany("Logs")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.ChampionshipMatch", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Championship", "Championship")
                        .WithMany("Matches")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany("ChampionshipMatches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.ChampionshipStanding", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Championship", "Championship")
                        .WithMany("Standings")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PaymentSchedule", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Player", "Player")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PlayerLog", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Player", "Player")
                        .WithMany("Logs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PlayerRebuy", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Player", "Player")
                        .WithMany("Rebuys")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany("Rebuys")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PokerTable", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany("Tables")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Tournament", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.BlindStructure", "BlindStructure")
                        .WithMany()
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.TournamentTemplate", "Template")
                        .WithMany("TournamentsCreated")
                        .HasForeignKey("TemplateId");

                    b.Navigation("BlindStructure");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentLog", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentPlayer", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.Player", "Player")
                        .WithMany("TournamentParticipations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerTournamentDirector.Models.PokerTable", "Table")
                        .WithMany("Players")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokerTournamentDirector.Models.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Table");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentTemplate", b =>
                {
                    b.HasOne("PokerTournamentDirector.Models.BlindStructure", "BlindStructure")
                        .WithMany()
                        .HasForeignKey("BlindStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlindStructure");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.BlindStructure", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Championship", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Matches");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Player", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("PaymentSchedules");

                    b.Navigation("Rebuys");

                    b.Navigation("TournamentParticipations");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.PokerTable", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.Tournament", b =>
                {
                    b.Navigation("ChampionshipMatches");

                    b.Navigation("Players");

                    b.Navigation("Rebuys");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("PokerTournamentDirector.Models.TournamentTemplate", b =>
                {
                    b.Navigation("TournamentsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
